import { Movie } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Cyberpunk Horizons',
    description: 'In a future where neon lights hide dark secrets, one hacker must infiltrate the mainframe to save her sister from a digital eternity.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1535295972055-1c762f4483e5?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1535295972055-1c762f4483e5?w=1600&auto=format&fit=crop&q=80',
    genre: ['Sci-Fi', 'Action'],
    rating: 'TV-MA',
    matchScore: 98,
    year: 2024,
    duration: '2h 15m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    featured: true,
    contentType: 'movie'
  },
  {
    id: '2',
    title: 'The Last Frontier',
    description: 'A documentary following the brave souls who live in the most remote corners of Alaska, fighting the elements to survive.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1444464666117-be651b96d896?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1444464666117-be651b96d896?w=1600&auto=format&fit=crop&q=80',
    genre: ['Documentary', 'Drama'],
    rating: 'TV-14',
    matchScore: 95,
    year: 2023,
    duration: '1h 45m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    contentType: 'movie'
  },
  {
    id: '3',
    title: 'Midnight Racer',
    description: 'The underground racing scene in Tokyo heats up when a newcomer challenges the reigning king of the drift.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1600&auto=format&fit=crop&q=80',
    genre: ['Action', 'Drama'],
    rating: 'PG-13',
    matchScore: 88,
    year: 2022,
    duration: '1h 58m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    contentType: 'movie'
  },
  {
    id: '4',
    title: 'Echoes of Silence',
    description: 'A psychological thriller about a musician who starts hearing melodies that predict the future.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&auto=format&fit=crop&q=80',
    genre: ['Drama', 'Sci-Fi'],
    rating: 'R',
    matchScore: 92,
    year: 2023,
    duration: '2h 05m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    contentType: 'movie'
  },
  {
    id: '5',
    title: 'Laugh Track',
    description: 'A struggling comedian finds out his life is actually a sitcom watched by aliens.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=1600&auto=format&fit=crop&q=80',
    genre: ['Comedy', 'Sci-Fi'],
    rating: 'TV-14',
    matchScore: 85,
    year: 2024,
    duration: '30m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    contentType: 'movie'
  },
  {
    id: '6',
    title: 'Deep Blue',
    description: 'Exploration of the deepest parts of the ocean reveals creatures never seen before.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1582967788606-a171f1080ca8?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1582967788606-a171f1080ca8?w=1600&auto=format&fit=crop&q=80',
    genre: ['Documentary'],
    rating: 'G',
    matchScore: 99,
    year: 2021,
    duration: '50m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    contentType: 'movie'
  },
  {
    id: '7',
    title: 'Urban Legends',
    description: 'A group of teenagers investigates the local myths of their hometown, only to find they are real.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    genre: ['Trending', 'Drama'],
    rating: 'TV-MA',
    matchScore: 94,
    year: 2023,
    duration: '1h 40m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    contentType: 'movie'
  },
  {
    id: '8',
    title: 'Cosmic Voyage',
    description: 'Interstellar travel has never been this dangerous. A crew of misfits tries to save the galaxy.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&auto=format&fit=crop&q=60',
    backdropUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80',
    genre: ['Sci-Fi', 'Trending'],
    rating: 'PG',
    matchScore: 97,
    year: 2024,
    duration: '2h 30m',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    contentType: 'movie'
  }
];